--- # my second YAML playbook
- hosts: demall
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars_prompt:
   - name: pkg_name
     prompt: Your package to be installed
  tasks:
   - name: Install httpd on servers
     yum: pkg='{{ pkg_name}}' state=absent

