--- # my second YAML playbook
- hosts: demall
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Install httpd on servers
     yum: pkg=httpd state=installed
   - name: Wait for the service to start listening on port 80
     wait_for:
       port: 80
       state: started
     notify: Stop Httpd
  handlers:
   - name: Stop Httpd
     action: service name=httpd state=stopped
