--- # Outline to playbook Translation
 - hosts: all
   user: ansible
   sudo: yes
   gather_facts: no
   tasks:
    - name: date/time stamp for plabook start
      raw: /usr/bin/date >> /home/ansible/playbook07.log
    - name: Install the apache web server
      yum: pkg=httpd state=latest
      notify: restart the HTTPD
    - name: install client software-Telnet
      yum: pkg=telnet state=latest
    - name: log all the packages installed
      raw: yum list installed | grep telnet >> /home/ansible/playbook07.log
    - name: date/time stamp for playbook end
      raw: /usr/bin/date >> /home/ansible/playbook07.log
   handlers:
    - name: restart the HTTPD
      action: service name=httpd state=restarted
