---
 - hosts: droplets
   user: ansible
   sudo: yes
   connection: ssh
   tasks:
    - name: install nginx
      apt: pkg=nginx state=installed
      notify:
       - start nginx
    - name: upload default index.php for host
      copy: src=static_files/index.php dest=/usr/share/nginx/www/ mode=0644
      register: php
      ignore_errors: True
    - name: remove index.html for host
      command: rm /usr/share/nginx/www/index.html
      when: php|success
    - name: upload default index.php for host
      copy: src=static_files/index.php dest=/usr/share/nginx/www/ mode=0644
      when: php|failed
   handlers:
    - name: start nginx
      service: name=nginx state=started
